import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Fragment } from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Text } from '../components/AppText';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '../theme/colors';

// Public, unauthenticated route (App Store Connect's "Privacy Policy URL"
// field, and Apple's reviewers, need to reach this without signing in) —
// deployed automatically to https://haven-ly.com/privacy alongside the
// rest of the web build (see .github/workflows/deploy-web.yml). No auth
// gate wraps it, same as /sign-in.
//
// Update this whenever what the app actually collects/shares changes —
// EFFECTIVE_DATE below and the collection lists in SECTIONS should track
// reality, not the other way around.
const EFFECTIVE_DATE = 'August 29, 2026';
const CONTACT_EMAIL = 'joshuaefron5890@gmail.com';

type Section = { heading: string; paragraphs: string[]; bullets?: string[] };

const SECTIONS: Section[] = [
  {
    heading: 'What Haven.ly is',
    paragraphs: [
      'Haven.ly ("Haven.ly," "we," "us") is an app that helps families with neurodivergent children connect with other families in their local community — matching, messaging, playdate proposals, local events, and curated resources. This policy explains what information we collect through the app, how we use it, and who we share it with.',
      'Haven.ly is intended for use by parents and guardians (18 and older) on behalf of their family. It is not directed at children, and children do not create their own accounts or interact with the app directly — any information about a child is entered by their parent or guardian.',
    ],
  },
  {
    heading: 'Information we collect',
    paragraphs: ['We collect the information you give us directly, plus a small amount generated by using the app:'],
    bullets: [
      'Account information: your email address and password, or, if you sign in with Google, your name, email address, and profile photo as provided by Google.',
      'Family profile: your name, pronouns, city/state/zip code, and family photo.',
      'Child and sibling profiles: name, age, grade, school, photo, and neurodivergence-related information you choose to share, entered by you.',
      'Preferences: play style, interests, goals, personality, and availability, used to power matching and suggested playdate times.',
      'Messages and playdate activity: messages you send to other families, playdate proposals, and posts you make to community boards.',
      'Sitter profiles (if you register as a sitter): name, contact information, bio, photo, credentials, and background-check status.',
      'Calendar availability (only if you connect Google Calendar): we receive free/busy time ranges, not the titles, descriptions, or attendees of your events. If you’re a sitter and choose to let Haven.ly add your confirmed playdates to your calendar, we also create calendar events on your behalf for that purpose only.',
      'A device push-notification token, so we can deliver notifications about messages and playdate activity.',
    ],
  },
  {
    heading: 'How we use this information',
    paragraphs: [
      'We use the information above to run Haven.ly: to match your family with compatible families nearby, enable messaging and playdate proposals, show local events and schools near you, send push notifications about activity relevant to you, and show curated content (podcasts, articles, products) relevant to your family.',
    ],
  },
  {
    heading: 'How we share information',
    paragraphs: ['We do not sell your personal information. We share it only as follows:'],
    bullets: [
      'With other Haven.ly families: a limited profile (first name, general location, child’s age/interests/neurodivergence tags relevant to matching) is visible to other families for matching and messaging purposes — not your exact address, email, or phone number unless you choose to share it in a message.',
      'Service providers who host and run the app on our behalf: Google Firebase (authentication, database, hosting), Google Calendar API (only if you connect it), Expo (push notification delivery), and Resend (transactional email, e.g. family invites).',
      'Apple, when you install the app through TestFlight or the App Store — Apple collects its own device and diagnostic data under Apple’s own privacy policy, separate from this one.',
      'If required by law, or to protect the safety of our users.',
    ],
  },
  {
    heading: 'Our use of Google user data',
    paragraphs: [
      'If you connect Google Calendar, Haven.ly requests access to your free/busy availability so we can flag scheduling conflicts and suggest playdate times — never the titles, descriptions, locations, or attendees of your actual events. Sitters may separately choose to grant Haven.ly permission to create calendar events for their own confirmed playdates.',
      'If you sign in with Google, we receive the name, email address, and profile photo Google shares as part of that sign-in.',
      'We use this information solely to provide the Haven.ly features described in this policy — matching, scheduling, and account sign-in — and never to serve ads or sell it. It’s shared only with the service providers listed above, to the extent needed to operate those features, and is retained only as long as your account and the relevant connection stay active; disconnecting Google Calendar (see “Your choices” below) or deleting your account stops any further access and removes what we’ve stored.',
      'Haven.ly’s use and transfer of information received from Google APIs to any other app will adhere to the Google API Services User Data Policy, including the Limited Use requirements.',
    ],
  },
  {
    heading: 'Your choices',
    paragraphs: [
      'You can review and edit your family, child, and preference information at any time from your Profile. You can disconnect Google Calendar from Profile as well; sitters can do the same from their availability screen.',
      'You can permanently delete your account from Profile → Delete account. This removes your profile and related records and deletes your sign-in credentials; messages, playdate proposals, and community posts you’ve already sent remain visible to the other people in those conversations, the same way most messaging apps handle a deleted account’s message history.',
    ],
  },
  {
    heading: 'Data security',
    paragraphs: [
      'Data is transmitted over encrypted connections and stored with Google Firebase, with access restricted to what each part of the app needs. No method of transmission or storage is 100% secure, but we work to protect your information appropriately for what we collect.',
    ],
  },
  {
    heading: 'Changes to this policy',
    paragraphs: [
      'If we make material changes to this policy, we’ll update the effective date below. Continued use of Haven.ly after a change means you accept the updated policy.',
    ],
  },
  {
    heading: 'Contact us',
    paragraphs: [`Questions about this policy or your data? Reach us at ${CONTACT_EMAIL}.`],
  },
];

export default function PrivacyPolicy() {
  const goBack = () => {
    if (router.canGoBack()) {
      router.back();
    } else if (Platform.OS === 'web') {
      window.location.href = '/';
    } else {
      router.replace('/');
    }
  };

  return (
    <SafeAreaView style={styles.screen} edges={['top', 'bottom']}>
      <View style={styles.header}>
        <Pressable style={styles.back} onPress={goBack} hitSlop={8}>
          <Ionicons name="chevron-back" size={20} color={colors.text} />
        </Pressable>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.effectiveDate}>Effective {EFFECTIVE_DATE}</Text>

        {SECTIONS.map((section) => (
          <Fragment key={section.heading}>
            <Text style={styles.sectionHeading}>{section.heading}</Text>
            {section.paragraphs.map((p) => (
              <Text key={p} style={styles.paragraph}>
                {p}
              </Text>
            ))}
            {section.bullets?.map((b) => (
              <View key={b} style={styles.bulletRow}>
                <Text style={styles.bulletDot}>{'•'}</Text>
                <Text style={styles.bulletText}>{b}</Text>
              </View>
            ))}
          </Fragment>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    gap: 12,
  },
  back: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  content: {
    padding: 20,
    paddingBottom: 48,
    maxWidth: 680,
  },
  effectiveDate: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 20,
  },
  sectionHeading: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginTop: 20,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 21,
    marginBottom: 10,
  },
  bulletRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    paddingRight: 4,
  },
  bulletDot: {
    fontSize: 14,
    color: colors.textMuted,
    lineHeight: 21,
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    color: colors.text,
    lineHeight: 21,
  },
});
